name: fes_brochure
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  http: ^0.13.3
  photo_view: ^0.11.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'images\icon.png'
  adaptive_icon_background: 'images\icon_bg.png'
  adaptive_icon_foreground: 'images\icon_fg.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data/
    - assets/images/
    - assets/images/logo_wIcon_dark.png
    - assets/images/logo_wIcon_light.png
    - assets/images/logo_woIcon_dark.png
    - assets/images/logo_woIcon_light.png
    - assets/images/covers/1.png
    - assets/images/covers/2.png
    - assets/images/covers/3.png
    - assets/images/covers/4.png
    - assets/images/covers/5.png
    - assets/images/covers/6.png
    - assets/images/covers/7.png
    - assets/images/covers/8.png
    - assets/images/covers/9.png
    - assets/images/covers/10.png
    - assets/images/covers/11.png
    - assets/images/covers/12.png
    - assets/images/covers/101.png
    - assets/images/covers/102.png
    - assets/images/covers/103.png
    - assets/images/covers/104.png
    - assets/images/covers/105.png
    - assets/images/covers/106.png
    - assets/images/covers/107.png
    - assets/images/covers/108.png
    - assets/images/covers/109.png
    - assets/images/covers/110.png
    - assets/images/covers/111.png
    - assets/images/covers/112.png
    - assets/images/covers/113.png
    - assets/images/covers/114.png
    - assets/images/covers/115.png
    - assets/images/covers/116.png
    - assets/images/covers/117.png
    - assets/images/covers/1001.png
    - assets/images/covers/1002.png
    - assets/images/maps/1.png
    - assets/images/maps/2.png
    - assets/images/maps/3.png
    - assets/images/maps/4.png
    - assets/images/maps/5.png
    - assets/images/maps/6.png
    - assets/images/maps/7.png
    - assets/images/maps/8.png
    - assets/images/maps/9.png
    - assets/images/maps/10.png
    - assets/images/maps/11.png
    - assets/images/maps/12.png
    - assets/images/maps/101.png
    - assets/images/maps/102.png
    - assets/images/maps/103.png
    - assets/images/maps/104.png
    - assets/images/maps/105.png
    - assets/images/maps/106.png
    - assets/images/maps/107.png
    - assets/images/maps/108.png
    - assets/images/maps/109.png
    - assets/images/maps/110.png
    - assets/images/maps/111.png
    - assets/images/maps/112.png
    - assets/images/maps/113.png
    - assets/images/maps/114.png
    - assets/images/maps/115.png
    - assets/images/maps/116.png
    - assets/images/maps/117.png
    - assets/images/maps/1001.png
    - assets/images/maps/1002.png
    - assets/splash/fg.png
    - assets/splash/bg.png
    - assets/splash/splash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Black.otf
          weight: 900
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
